### ISSUE TITLE
Consider breaking down "Misc" into new categories

### ISSUE THREAD

**Issue by ctrlplusb** [jaredpalmer/awesome-react-render-props#63]
Looking through the "Misc" category I see opportunities for new categories.

## State

  - react-value: An easy easy way to wrap controlled components that provide value and onChange props with state.
  - react-redux-local: Simple local reducer with middleware/sagas/redux-dev-tools support.
  - redux-render: Ergonomic Redux bindings for React using render props
  - unstated: Share state between components with the same statefu
  - react-gizmo: UI Finite State Machine for React

Alternatively the above could be merged into "Data".

## Composition

  - react-powerplug: Renderless Pluggable State Containers
  - react-adopt: 😎 Compose render props components like a pro.
  - react-composer: Compose render prop components
  - `@danwang/retainer`: Compose render prop components by lifting computation into containers

## Media

  - react-power-picture: Progressively load an image srcset for maximum responsiveness and performance
  - react-with-async-fonts: Module for dealing with custom web fonts
  - react-progressive-image: React component for progressive image loading

## Timing

  - react-loads: A simple React component to handle loading state
  - react-sentinel: Abstracts away requestAnimationFrame, allowing you to poll anything for props
  - react-pro-metronome: React component for creating your own metronome
  - react-t-minus: A React component to handle simple countdowns.

---  

This would then result in misc only containing the following:

  - react-pledge: Declarative way to track promise lifecycle states using "render props" 🕶
  - react-device-battery: 🔋 Notifies your React App of the device battery status
  - react-geolocation: Declarative geolocation in React
  - react-albus: React component library for building declarative multi-step flows (wizards).
  - `@tedconf/react-show-more`: A Unopinionated component to handle showing more items
  - react-treefold: A renderless tree component for your hierarchical React views
  - react-google-calendar-events-list: React component which retrieves events from a google calendar.
  - react-google-maps-loader: Simple loader to use google maps services
  - react-render-fam: Lit components for conditional rendering in React

**Comment by kentcdodds** [comment]
Yes, feel free to make a PR. Maybe @jaredpalmer could add you as a collaborator?

**Comment by jaredpalmer** [comment]
Yeah will do.

**Comment by jaredpalmer** [comment]
Invited!

**Comment by ctrlplusb** [comment]
Rad, thanks gents. Shall get on this one tomorrow 👍

**Comment by ctrlplusb** [comment]
Waiting for #67 to land to avoid extra work on either side.
